properties([pipelineTriggers([githubPush()])])
pipeline {
    agent any
    stages {
        stage('prepare') {
            steps {
                git url: 'https://github.com/matthias-luger/hypixel-react',
                    branch: 'k8s'
            }
        }
        stage('build') {
            steps {
                script {
                    def customImage = docker.build("flou21/hypixel-react:${env.BUILD_ID}")
                }
            }
        }
    }
}
